### ISSUE TITLE
Postgres migrations broke on 1.4.1

### ISSUE THREAD

**Issue by jaska120** [markusahlstrand/knex-data-api-client#45]
Hi,

I just started to use your awesome library. I started with latest version `1.4.2` but could not get the migrations to work on `postgres`. I tried it multiple times on fresh database with no luck.

See my attached log from `knex migrate:latest --debug` command:

```
[
  {
    sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'knex_migrations' ],
    output: [Function: output]
  }
]
[
  {
    sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'knex_migrations_lock' ],
    output: [Function: output]
  }
]
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'J8ebRgCSTq9fVCRIBh9Op',
  sql: 'select * from "knex_migrations_lock"'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'HRewO9CjQ1BJ0S2vdBO0g',
  sql: 'select "name" from "knex_migrations" order by "id" asc'
}
{
  method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 0 ],
  __knexQueryUid: 'eDdSGhYPYGhUbJdbAgeC4',
  sql: 'update "knex_migrations_lock" set "is_locked" = ? where "is_locked" = ?',
  returning: undefined
}
Can't take lock to run migrations: Migration table is already locked
If you are sure migrations are not running you can release the lock manually by running 'knex migrate:unlock'
undefined
```

I can confirm that migrations run fine by downgrading to `1.4.0`.

**Comment by jaska120** [comment]
The issue was introduced in `1.4.1` when dialect check for `mysql` was added. The relevant lines can been seen from below.
https://github.com/markusahlstrand/knex-data-api-client/blob/aeb9f7c09ec0d6971f27c3a7d0402ba89a77d768/src/data-api.js#L149-L153

In all my manual tests, `postgres` retrurns always `obj.response.numberOfRecordsUpdated` instead of `obj.response.records` on `UPDATE` and `DEL` statements.

**Comment by markusahlstrand** [comment]
Thanks for reporting this issue!

We did a fix for returning('*') on update request which probably broke the behaviour when not returning the updated entity. I'll go ahead and add a new test for this and patch the code.

**Comment by markusahlstrand** [comment]
Published 1.4.3 which I think should fix it. Let me know if the migrations work for you with this update.

**Comment by jaska120** [comment]
I can confirm that the issue was fixed on `1.4.3`. Thanks @markusahlstrand

**Comment by pats110217** [comment]
Still experiencing migration issues on 1.4.3 

`Tue Jan 19 05:07:24 UTC 2021 : Endpoint response body before transformations: {"errorType":"object","errorMessage":"MigrationLocked: Migration table is already locked","trace":[]}
Tue Jan 19 05:07:24 UTC 2021 : Lambda execution failed with status 200 due to customer function error: MigrationLocked: Migration table is already locked. Lambda request id: d828a688-3a53-4ba0-9b23-ce1511c64754`

**Comment by markusahlstrand** [comment]
Hi @pats110217 !

I think this might be an issue with that the previous migration didn't complete successfully and never released the lock. Try removing any items from the knex_migrations_lock and then run the migrations again.
